export enum queryKeys {
    // admin
    LOGIN = "LOGIN",
    GET_DASHBOARD = "GET_DASHBOARD",
    GET_ADMIN_INFO = "GET_ADMIN_INFO",

    // clinics
    CREATE_CLINIC = "CREATE_CLINIC",
    GET_CLINICS = "GET_CLINICS",
    GET_SINGLE_CLINIC = "GET_SINGLE_CLINIC",
    UPDATE_CLINIC = "UPDATE_CLINIC",
    DELETE_CLINIC = "DELETE_CLINIC",

    // working hours
    CREATE_WORKING_HOURS = "CREATE_WORKING_HOURS",
    UPDATE_WORKING_HOURS = "UPDATE_WORKING_HOURS",
    DELETE_WORKING_HOURS = "DELETE_WORKING_HOURS",
    GET_WORKING_HOURS = "GET_WORKING_HOURS",
    GET_SINGLE_WORKING_HOURS = "GET_SINGLE_WORKING_HOURS",
}
